In [44]:
import numpy as np
import pandas as pd
import openpyxl
from sklearn.preprocessing import LabelEncoder

from utils import * # Dataloader and K-fold mechanism 
from SATreeCraft import * # Tree solver framework
from SATreeClassifier import * 
import time

In [45]:
features = np.array(['0', '1'])
dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15,5],[15,6]])  # Dataset X
epsilon = 0.1
k_clusters = 3
depth = 2

# CL_pairs = np.array([])
ML_pairs = np.array([])
CL_pairs = np.array([[2,3]])
# # ML_pairs = np.array([[4,5],[0,1],[2,3]])

clustering_problem = max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                                                  features= features,
                                                                  k_clusters= k_clusters,
                                                                  #ML_pairs= ML_pairs,
                                                                  CL_pairs= CL_pairs,
                                                                  epsilon = epsilon,
                                                                  fixed_depth= depth
                                             )


In [46]:
loandra_path = '/Users/harisrasul/Desktop/loandra'
clustering_problem.solve()
print(clustering_problem.cluster_assignments)
print(clustering_problem.cluster_diameters)

{0: [2, 4, 5], 1: [3], 2: [0, 1]}
{0: 8.246211251235321, 1: 0, 2: 1.0}


Wine

In [47]:
from utils import *

file_path_to_test = 'Datasets/wine/wine.data'
delimiter = ','
label_position = 0 

data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)



print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)


features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'] (13,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] (178,)
Dataset:
 [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] (178, 13)


In [48]:
loandra_path = '/Users/harisrasul/Desktop/loandra'

epsilon = 0.1 
k_clusters = 3

CL_pairs = np.array([])
ML_pairs = np.array([])

for depth in range(2, 5):  # This will iterate over 2, 3, and 4
    start_time = time.time()
    clustering_problem = SATreeCraft(dataset=dataset,
                                     features=features,
                                     k_clusters=k_clusters,
                                     ML_pairs=ML_pairs,
                                     CL_pairs=CL_pairs,
                                     epsilon=epsilon,
                                     fixed_depth=depth)
    
    clustering_problem.solve_loandra(loandra_path)
    end_time = time.time()
    duration = end_time - start_time
    print(f"Results for depth {depth}:")
    print(clustering_problem.cluster_assignments)
    print(clustering_problem.cluster_diameters)
    print(f"Time Taken: {duration:.2f} seconds")
    print("----------------------------------------")

Results for depth 2:
{0: [3, 5, 6, 7, 10, 11, 12, 14, 15, 16, 18, 27, 30, 31, 33, 49, 51, 53, 57, 58], 1: [4, 43, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 71, 72, 75, 76, 77, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 142, 143, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 169, 170, 171, 172, 177], 2: [0, 1, 2, 8, 9, 13, 17, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 50, 52, 54, 55, 56, 68, 70, 73, 74, 78, 95, 141, 144, 145, 157, 168, 173, 174, 175, 176]}
{0: 445.6713932933098, 1: 458.13320879412356, 2: 455.06176152254324}
Time Taken: 16.74 seconds
----------------------------------------
Results for depth 3:
{0: [4, 43, 59, 60, 61, 62

Iris

In [49]:
file_path_to_test = 'Datasets/iris/iris.data'
label_position = -1 
delimiter = ','
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3'] (4,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] (150,)
Dataset:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 

In [50]:
loandra_path = '/Users/harisrasul/Desktop/loandra'
epsilon = 0.1 
k_clusters = 3

CL_pairs = np.array([])
ML_pairs = np.array([])

for depth in range(2, 5):  # This will iterate over 2, 3, and 4
    start_time = time.time()
    clustering_problem = SATreeCraft(dataset=dataset,
                                     features=features,
                                     k_clusters=k_clusters,
                                     ML_pairs=ML_pairs,
                                     CL_pairs=CL_pairs,
                                     epsilon=epsilon,
                                     fixed_depth=depth)
    
    clustering_problem.solve_loandra(loandra_path)
    end_time = time.time()
    duration = end_time - start_time
    print(f"Results for depth {depth}:")
    print(clustering_problem.cluster_assignments)
    print(clustering_problem.cluster_diameters)
    print(f"Time Taken: {duration:.2f} seconds")
    print("----------------------------------------")

Results for depth 2:
{0: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 99, 101, 106, 113, 114, 119, 121, 123, 126, 127, 138, 142, 146, 149], 1: [83, 100, 102, 103, 104, 105, 107, 108, 109, 110, 111, 112, 115, 116, 117, 118, 120, 122, 124, 125, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 139, 140, 141, 143, 144, 145, 147, 148], 2: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 98]}
{0: 2.7018512172212596, 1: 2.6495282598983545, 2: 2.6057628441590768}
Time Taken: 0.87 seconds
----------------------------------------
Results for depth 3:
{0: [50, 52, 76, 77, 100, 102, 103, 104, 105, 107, 108, 109, 110, 111, 112, 115, 116, 117, 118, 120, 122, 124, 125, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 

Ionosphere

In [51]:
file_path_to_test = 'Datasets/ionosphere/ionosphere.data'
label_position = -1 
delimiter = ','
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33'] (34,)
Labels: [0 1] (2,)
True Labels for Points: [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (351,)
Dataset:
 [[ 1.       0.       0.99539 ... -0.54487  0.18

In [52]:
loandra_path = '/Users/harisrasul/Desktop/loandra'
epsilon = 0.1 
k_clusters = 3
CL_pairs = np.array([])
ML_pairs = np.array([])

for depth in range(2, 5):  # This will iterate over 2, 3, and 4
    start_time = time.time()
    clustering_problem = SATreeCraft(dataset=dataset,
                                     features=features,
                                     k_clusters=k_clusters,
                                     ML_pairs=ML_pairs,
                                     CL_pairs=CL_pairs,
                                     epsilon=epsilon,
                                     fixed_depth=depth)
    
    clustering_problem.solve_loandra(loandra_path)
    end_time = time.time()
    duration = end_time - start_time
    print(f"Results for depth {depth}:")
    print(clustering_problem.cluster_assignments)
    print(clustering_problem.cluster_diameters)
    print(f"Time Taken: {duration:.2f} seconds")
    print("----------------------------------------")

Results for depth 2:
{0: [17, 21, 23, 41, 45, 49, 52, 53, 55, 59, 98, 102, 108, 110, 122, 124, 134, 136, 159, 163, 165, 166, 167, 170, 172, 176, 182, 184, 185, 187, 190, 204, 206, 215, 224, 232, 240, 242, 248, 255, 339], 1: [3, 5, 7, 9, 11, 13, 14, 15, 16, 18, 19, 27, 28, 33, 37, 38, 39, 40, 42, 43, 47, 57, 58, 60, 62, 63, 65, 66, 69, 70, 72, 73, 74, 76, 77, 78, 79, 81, 82, 83, 85, 88, 89, 90, 91, 95, 96, 97, 99, 104, 106, 111, 112, 113, 114, 117, 120, 123, 125, 131, 133, 135, 137, 138, 139, 140, 146, 147, 150, 151, 155, 160, 161, 164, 168, 173, 174, 175, 177, 188, 189, 192, 193, 197, 198, 199, 203, 205, 207, 209, 211, 212, 213, 214, 217, 218, 219, 221, 223, 225, 226, 229, 230, 231, 233, 234, 235, 236, 237, 238, 239, 246, 256, 258, 259, 261, 262, 263, 264, 265, 266, 267, 268, 271, 272, 274, 275, 277, 278, 279, 280, 281, 286, 287, 289, 291, 305, 307, 308, 317, 318, 319, 322, 329, 330, 331, 332, 333, 334, 335, 341, 344, 345, 346, 347, 348, 350], 2: [0, 1, 2, 4, 6, 8, 10, 12, 20, 22, 24, 