In [1]:
import numpy as np
from scipy.spatial import distance_matrix

dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15, 5], [15, 6]])
epsilon = 1

# Calculate the distance matrix
dist_matrix = distance_matrix(dataset, dataset)

# Extract the unique distances, excluding the diagonal (distance from a point to itself)
unique_distances = np.unique(dist_matrix[np.triu_indices_from(dist_matrix, k=1)])
unique_distances.sort()

# Initialize distance classes
distance_classes = []
current_class = []

# Group distances into classes based on epsilon
for dist in unique_distances:
    if not current_class or dist - current_class[0] <= epsilon:
        # If the current class is empty or the distance is within epsilon, add it to the class
        current_class.append(dist)
    else:
        # Otherwise, start a new class
        distance_classes.append(current_class)
        current_class = [dist]

if current_class:
    distance_classes.append(current_class)

# Display the distance classes
for i, d_class in enumerate(distance_classes):
    print(f"Distance class {i}: {d_class}")

Distance class 0: [1.0]
Distance class 1: [7.810249675906654, 8.06225774829855, 8.246211251235321, 8.48528137423857, 8.54400374531753]
Distance class 2: [9.219544457292887]
Distance class 3: [14.317821063276353, 14.560219778561036, 14.866068747318506]


In [7]:
import numpy as np
from itertools import combinations
from collections import defaultdict, OrderedDict

def create_distance_classes(dataset, epsilon=0):
    def euclidean_distance(point1, point2):
        return np.sqrt(np.sum((np.array(point1) - np.array(point2))**2))
    distances = {}
    for (idx1, point1), (idx2, point2) in combinations(enumerate(dataset), 2):
        dist = euclidean_distance(point1, point2)
        distances[(idx1, idx2)] = dist

    sorted_distances = sorted(distances.items(), key=lambda item: item[1])

    distance_classes_with_dist = OrderedDict()
    distance_classes_simplified = OrderedDict()
    current_class_label = 1
    for (pair, dist) in sorted_distances:
        placed = False
        for d_class, pairs in distance_classes_with_dist.items():
            class_dist = next(iter(pairs))[1]  # Get the reference distance for this class
            if abs(class_dist - dist) <= epsilon:
                distance_classes_with_dist[d_class].append((pair, dist))
                distance_classes_simplified[d_class].append(pair)
                placed = True
                break
        if not placed:
            distance_classes_with_dist[f'D{current_class_label}'] = [(pair, dist)]
            distance_classes_simplified[f'D{current_class_label}'] = [pair]
            current_class_label += 1
    
    return distance_classes_with_dist, distance_classes_simplified

# Example usage
dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15,5],[15,6]])
dist_classes_with_dist, dist_classes_simplified = create_distance_classes(dataset, epsilon=1)

# Print the simplified distance classes
for d_class, pairs in dist_classes_simplified.items():
    print(f"{d_class}: {pairs}")

def convert_to_numpy_array(distance_classes_simplified):
    # Extract the pairs for each class and convert them to a numpy array
    numpy_arrays = [np.array(pairs) for pairs in distance_classes_simplified.values()]
    return numpy_arrays

# Convert the simplified distance classes to numpy array
distance_classes = convert_to_numpy_array(dist_classes_simplified)

# Display the numpy arrays
distance_classes

D1: [(0, 1), (2, 3), (4, 5)]
D2: [(1, 2), (2, 5), (2, 4), (3, 5), (0, 2), (1, 3), (3, 4)]
D3: [(0, 3)]
D4: [(1, 4), (0, 4), (1, 5), (0, 5)]


[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[1, 2],
        [2, 5],
        [2, 4],
        [3, 5],
        [0, 2],
        [1, 3],
        [3, 4]]),
 array([[0, 3]]),
 array([[1, 4],
        [0, 4],
        [1, 5],
        [0, 5]])]

In [5]:
for w, pairs_array in enumerate(distance_classes):
    for pair in pairs_array:
        i, i_prime = pair
        print("distnace class w = ",w)
        print("The pair of points is in here: ", pair)

distnace class w =  0
The pair of points is in here:  [0 1]
distnace class w =  0
The pair of points is in here:  [2 3]
distnace class w =  0
The pair of points is in here:  [4 5]
distnace class w =  1
The pair of points is in here:  [1 2]
distnace class w =  2
The pair of points is in here:  [2 5]
distnace class w =  3
The pair of points is in here:  [2 4]
distnace class w =  3
The pair of points is in here:  [3 5]
distnace class w =  4
The pair of points is in here:  [0 2]
distnace class w =  4
The pair of points is in here:  [1 3]
distnace class w =  5
The pair of points is in here:  [3 4]
distnace class w =  6
The pair of points is in here:  [0 3]
distnace class w =  7
The pair of points is in here:  [1 4]
distnace class w =  8
The pair of points is in here:  [0 4]
distnace class w =  8
The pair of points is in here:  [1 5]
distnace class w =  9
The pair of points is in here:  [0 5]


In [6]:
for w in range(1, len(distance_classes)):  # Starting from 1 since we're checking w against w-1
    print(w-1,w)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9


In [7]:
CL_pairs = np.array([[ 1,2], [3,4]])
for i, i_prime in CL_pairs:
    print(i,i_prime)


1 2
3 4
