In [1]:
import numpy as np
import pandas as pd
import openpyxl
from sklearn.preprocessing import LabelEncoder

from utils import * # Dataloader and K-fold mechanism 
from SATreeCraft import * # Tree solver framework
from SATreeClassifier import * 

In [2]:
file_path_to_test = 'Datasets/data_banknote_authentication.txt'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3'] (4,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 ... 1 1 1] (1372,)
Dataset:
 [[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]] (1372, 4)


In [3]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3, 4]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 44.37 seconds
Accuracies: [0.92       0.91272727 0.85766423 0.9379562  0.90145985]
Mean Score: 0.9059615129396151

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 45.75 seconds
Accuracies: [0.91272727 0.92363636 0.90510949 0.91240876 0.91605839]
Mean Score: 0.9139880557398806

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 43.89 seconds
Accuracies: [0.89090909 0.86909091 0.90510949 0.9379562  0.92335766]
Mean Score: 0.9052846715328468

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 42.35 seconds
Accuracies: [0.90909091 0.91272727 0.94160584 0.90145985 0.90875912]
Mean Score: 0.914728599867286

Iteration c

In [4]:
file_path_to_test = 'Datasets/breast+cancer+coimbra/dataR2.csv'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8'] (9,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1] (116,)
Dataset:
 [[ 48.          23.5         70.         ...   9.7024       7.99585
  417.114     ]
 [ 83.          20.69049454  92.         ...   5.429285     4.06405
  468.786     ]
 [ 82.          23.12467037  91.         ...  22.43204      9.27715
  554.697     ]
 ...
 [ 65.          32.05        97.         ...  22.54        10.33
  314.05      ]
 [ 72.          25.59        82.         ...  33.75         3.27
  392.46      ]
 [ 86.          27.18       138.         ...  14.11         4.35
   90.09      ]] (116, 9)


In [5]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3, 4]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 13.24 seconds
Accuracies: [0.75       0.73913043 0.7826087  0.7826087  0.7826087 ]
Mean Score: 0.7673913043478261

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 9.15 seconds
Accuracies: [0.70833333 0.69565217 0.73913043 0.7826087  0.52173913]
Mean Score: 0.6894927536231884

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 7.47 seconds
Accuracies: [0.70833333 0.60869565 0.73913043 0.86956522 0.73913043]
Mean Score: 0.7329710144927537

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 5.23 seconds
Accuracies: [0.79166667 0.86956522 0.82608696 0.56521739 0.73913043]
Mean Score: 0.7583333333333332

Iteration com

In [6]:
file_path_to_test = 'Datasets/Cryotherapy.xlsx'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5'] (6,)
Labels: [0 1] (2,)
True Labels for Points: [0 1 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0
 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1
 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1] (90,)
Dataset:
 [[1.000e+00 3.500e+01 1.200e+01 5.000e+00 1.000e+00 1.000e+02]
 [1.000e+00 2.900e+01 7.000e+00 5.000e+00 1.000e+00 9.600e+01]
 [1.000e+00 5.000e+01 8.000e+00 1.000e+00 3.000e+00 1.320e+02]
 [1.000e+00 3.200e+01 1.175e+01 7.000e+00 3.000e+00 7.500e+02]
 [1.000e+00 6.700e+01 9.250e+00 1.000e+00 1.000e+00 4.200e+01]
 [1.000e+00 4.100e+01 8.000e+00 2.000e+00 2.000e+00 2.000e+01]
 [1.000e+00 3.600e+01 1.100e+01 2.000e+00 1.000e+00 8.000e+00]
 [1.000e+00 5.900e+01 3.500e+00 3.000e+00 3.000e+00 2.000e+01]
 [1.000e+00 2.000e+01 4.500e+00 1.200e+01 1.000e+00 6.000e+00]
 [2.000e+00 3.400e+01 1.125e+01 3.000e+00 3.000e+00 1.500e+02]
 [2.000e+00 2.100e+01 1.075e+01 5.000e+00 1.000e+00 3.500e+01]
 [2.000e+00 1.500e+01 6

In [7]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3, 4]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 1.21 seconds
Accuracies: [1.         0.94444444 0.94444444 0.88888889 0.88888889]
Mean Score: 0.9333333333333332

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 1.17 seconds
Accuracies: [0.77777778 0.83333333 0.94444444 0.88888889 1.        ]
Mean Score: 0.888888888888889

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 1.10 seconds
Accuracies: [0.83333333 0.77777778 0.94444444 0.88888889 1.        ]
Mean Score: 0.888888888888889

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 1.01 seconds
Accuracies: [0.88888889 0.83333333 0.94444444 0.72222222 0.83333333]
Mean Score: 0.8444444444444444

Iteration comple

In [8]:
file_path_to_test = 'Datasets/Immunotherapy.xlsx'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6'] (7,)
Labels: [0 1] (2,)
True Labels for Points: [1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0
 1 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1
 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1] (90,)
Dataset:
 [[  1.    22.     2.25  14.     3.    51.    50.  ]
 [  1.    15.     3.     2.     3.   900.    70.  ]
 [  1.    16.    10.5    2.     1.   100.    25.  ]
 [  1.    27.     4.5    9.     3.    80.    30.  ]
 [  1.    20.     8.     6.     1.    45.     8.  ]
 [  1.    15.     5.     3.     3.    84.     7.  ]
 [  1.    35.     9.75   2.     2.     8.     6.  ]
 [  2.    28.     7.5    4.     1.     9.     2.  ]
 [  2.    19.     6.     2.     1.   225.     8.  ]
 [  2.    32.    12.     6.     3.    35.     5.  ]
 [  2.    33.     6.25   2.     1.    30.     3.  ]
 [  2.    17.     5.75  12.     3.    25.     7.  ]
 [  2.    15.     1.75   1.     2.    49.     7.  ]
 [  2.    15.     5.5   12.     1.  

In [9]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3, 4]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 1.49 seconds
Accuracies: [0.77777778 0.83333333 0.83333333 0.83333333 0.77777778]
Mean Score: 0.8111111111111112

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 1.33 seconds
Accuracies: [0.72222222 0.88888889 0.77777778 1.         0.83333333]
Mean Score: 0.8444444444444444

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 1.37 seconds
Accuracies: [0.94444444 1.         0.72222222 0.88888889 0.88888889]
Mean Score: 0.888888888888889

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 1.40 seconds
Accuracies: [0.88888889 0.83333333 0.77777778 0.77777778 0.72222222]
Mean Score: 0.8

Iteration complete
Iteration c

In [25]:
file_path_to_test = 'Datasets/iris/iris.data'
label_position = -1 
delimiter = ','
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3'] (4,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] (150,)
Dataset:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 

In [26]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3, 4]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 1.38 seconds
Accuracies: [0.93333333 0.93333333 0.96666667 0.93333333 0.9       ]
Mean Score: 0.9333333333333333

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 1.23 seconds
Accuracies: [0.93333333 0.96666667 0.93333333 0.93333333 0.9       ]
Mean Score: 0.9333333333333333

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 1.13 seconds
Accuracies: [1.         0.93333333 0.9        0.93333333 0.96666667]
Mean Score: 0.9466666666666667

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 1.12 seconds
Accuracies: [0.93333333 0.93333333 0.93333333 0.96666667 0.86666667]
Mean Score: 0.9266666666666665

Iteration comp

In [12]:
file_path_to_test = 'Datasets/Data_User_Modeling_Dataset_Hamdi_Tolga_KAHRAMAN.xls'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4'] (5,)
Labels: [0 1 2 3] (4,)
True Labels for Points: [3 0 1 2 1 2 2 3 1 0 0 1 2 0 2 0 3 1 1 2 1 2 2 1 1 0 3 1 0 0 2 1 1 0 0 1 1
 1 3 2 1 0 2 2 3 2 2 0 0 2 1 2 1 0 2 1 2 2 0 1 1 2 2 1 2 3 3 2 1 2 2 0 3 2
 0 3 1 1 3 1 1 2 2 1 1 3 0 1 1 2 2 2 3 1 0 1 1 0 2 1 1 0 2 1 1 2 2 2 2 0 1
 1 0 0 2 2 3 0 2 0 1 1 1 2 0 0 0 1 1 2 1 2 3 0 2 2 1 1 2 1 3 2 2 1 2 0 1 3
 1 0 0 1 3 1 2 2 2 0 2 2 1 2 0 0 3 0 2 0 1 0 1 2 0 1 2 1 1 0 2 0 1 0 0 1 1
 1 0 2 1 0 2 0 2 0 2 1 3 1 2 3 3 2 3 1 0 1 2 2 3 0 2 2 0 2 2 1 1 0 2 1 1 2
 2 2 1 0 2 1 0 0 2 1 1 0 2 1 1 0 2 2 1 0 2 1 2 0 2 1 0 2 2 2 1 0 2 0 2 0] (258,)
Dataset:
 [[0.   0.   0.   0.   0.  ]
 [0.08 0.08 0.1  0.24 0.9 ]
 [0.06 0.06 0.05 0.25 0.33]
 ...
 [0.54 0.82 0.71 0.29 0.77]
 [0.5  0.75 0.81 0.61 0.26]
 [0.66 0.9  0.76 0.87 0.74]] (258, 5)


In [13]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3, 4]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 4.59 seconds
Accuracies: [0.90384615 0.82692308 0.94230769 0.82352941 0.76470588]
Mean Score: 0.852262443438914

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 3.46 seconds
Accuracies: [0.88461538 0.82692308 0.84615385 0.84313725 0.88235294]
Mean Score: 0.8566365007541478

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 2.81 seconds
Accuracies: [0.86538462 0.96153846 0.80769231 0.78431373 0.84313725]
Mean Score: 0.8524132730015083

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 3.31 seconds
Accuracies: [0.90384615 0.84615385 0.86538462 0.78431373 0.82352941]
Mean Score: 0.8446455505279035

Iteration compl

In [14]:
file_path_to_test = 'Datasets/vertebral+column/verbex.data'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5'] (6,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (310,)
Dataset:
 [[ 63.0278175   22.55258597  39.60911701  40.47523153  98.67291675
   -0.25439999]
 [ 39.05695098  10.06099147  25.01537822  28.99595951 114.4054254
    4.56425864]
 [ 68.83202098  22.21848205  50.09219357  46.61353893 105.9851355
   -3.53031731]
 ...
 [ 61.44659663  2

In [15]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 21.75 seconds
Accuracies: [0.75806452 0.75806452 0.75806452 0.82258065 0.77419355]
Mean Score: 0.7741935483870968

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 24.10 seconds
Accuracies: [0.75806452 0.74193548 0.87096774 0.79032258 0.77419355]
Mean Score: 0.7870967741935484

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 21.67 seconds
Accuracies: [0.72580645 0.83870968 0.70967742 0.85483871 0.77419355]
Mean Score: 0.7806451612903226

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 19.14 seconds
Accuracies: [0.77419355 0.70967742 0.85483871 0.87096774 0.64516129]
Mean Score: 0.7709677419354839



In [16]:
file_path_to_test = 'Datasets/wine/wine.data'
delimiter = ','
label_position = 0 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'] (13,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] (178,)
Dataset:
 [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] (178, 13)


In [17]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 1.91 seconds
Accuracies: [0.91666667 0.94444444 0.88888889 0.91428571 0.94285714]
Mean Score: 0.9214285714285714

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 1.86 seconds
Accuracies: [0.88888889 0.94444444 0.94444444 0.97142857 0.91428571]
Mean Score: 0.9326984126984128

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 2.02 seconds
Accuracies: [0.91666667 0.94444444 0.94444444 1.         0.91428571]
Mean Score: 0.943968253968254

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 2.13 seconds
Accuracies: [0.97222222 0.88888889 0.86111111 0.88571429 0.94285714]
Mean Score: 0.9101587301587302

Iteration compl

In [20]:
file_path_to_test = 'Datasets/monk+s+problems/monks-2.train' # Update this to the path of your data file
delimiter = ' '
label_position = 0 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position, custom_exclude=[-1])
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5'] (6,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 1 0 1 1 0
 1 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0
 0 0 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0 1 0 0
 0 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1
 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0] (169,)
Dataset:
 [[1. 1. 1. 1. 2. 2.]
 [1. 1. 1. 1. 4. 1.]
 [1. 1. 1. 2. 1. 1.]
 ...
 [3. 3. 2. 3. 1. 1.]
 [3. 3. 2. 3. 2. 1.]
 [3. 3. 2. 3. 4. 2.]] (169, 6)


In [21]:
import time

# Assuming k_fold_tester_loandra is already defined and imports are handled

# Parameters
k = 5
depths = [2, 3, 4]
min_margin_levels = [1, 4, 10, 20]
loandra_path = '/Users/harisrasul/Desktop/loandra'


# Iterate through each combination of depth and minimum support level
for depth in depths:
    for min_margin in min_margin_levels:
        # Capture the start time
        start_time = time.time()

        # Execute the k-fold tester
        accuracies, mean_score = k_fold_tester_loandra(loandra_path=loandra_path,
                                                       k=k, depth=depth, dataset=dataset, 
                                                       true_labels_for_points=true_labels_for_points, 
                                                       labels=labels, features=features, 
                                                       min_margin_level= min_margin)
        
        # Capture the end time
        end_time = time.time()

        # Calculate the duration
        duration = end_time - start_time

        # Print or log the results including the time taken
        print(f"Depth: {depth}, Min Margin: {min_margin}, Time Taken: {duration:.2f} seconds")
        print(f"Accuracies: {accuracies}")
        print(f"Mean Score: {mean_score}\n")

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 1, Time Taken: 3.88 seconds
Accuracies: [0.61764706 0.5        0.61764706 0.5        0.63636364]
Mean Score: 0.574331550802139

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 4, Time Taken: 3.96 seconds
Accuracies: [0.58823529 0.67647059 0.5        0.5        0.66666667]
Mean Score: 0.5862745098039215

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 10, Time Taken: 4.37 seconds
Accuracies: [0.67647059 0.5        0.58823529 0.67647059 0.45454545]
Mean Score: 0.579144385026738

Iteration complete
Iteration complete
Iteration complete
Iteration complete
Iteration complete
Depth: 2, Min Margin: 20, Time Taken: 4.33 seconds
Accuracies: [0.67647059 0.55882353 0.61764706 0.47058824 0.57575758]
Mean Score: 0.5798573975044563

Iteration comple

KeyboardInterrupt: 