In [1]:
import numpy as np
import time
from satree.utils import TreeDataLoaderBinaryNumerical, TreeDataLoaderWithCategorical, k_fold_tester # Dataloader and K-fold mechanism
from satree.SATreeCraft import SATreeCraft # Tree solver framework
from satree.SATreeClassifier import SATreeClassifier

In [2]:
# Path to the loandra executable (recommended to use for faster solving). To install, follow: https://github.com/jezberg/loandra
loandra_path = "/home/dvm/projects/sat/loandra"  # Change as needed

Numerical Tests

In [3]:
file_path_to_test = '../data/wine/wine.data'
delimiter = ','
label_position = 0

data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)



print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)


features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'] (13,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] (178,)
Dataset:
 [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] (178, 13)


Min-Height Problem 100% Training Accuracy

In [4]:
min_height_numerical_problem = SATreeCraft(dataset=dataset,features=features,labels=labels,true_labels_for_points=true_labels_for_points)
min_height_numerical_problem.solve()
#min_height_numerical_problem.export_cnf_min_height("dimacs/testPerfectHeight.cnf")
print("Final Model: ", min_height_numerical_problem.model)
print("min depth found: ", min_height_numerical_problem.min_depth)

no solution at depth 1
no solution at depth 2
no solution at depth 3
Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('1'), 'threshold': np.float64(2.375)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('12'), 'threshold': np.float64(775.0)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('12'), 'threshold': np.float64(517.5)}, {'type': 'branching', 'children': [7, 8], 'feature': np.str_('0'), 'threshold': np.float64(13.35)}, {'type': 'branching', 'children': [9, 10], 'feature': np.str_('0'), 'threshold': np.float64(13.01)}, {'type': 'branching', 'children': [11, 12], 'feature': np.str_('0'), 'threshold': np.float64(13.04)}, {'type': 'branching', 'children': [13, 14], 'feature': np.str_('0'), 'threshold': np.float64(12.905000000000001)}, {'type': 'branching', 'children': [15, 16], 'feature': np.str_('11'), 'threshold': np.float64(1.585)}, {'type': 'branching', 'children': [17, 18], 'feature': np.str_('11'), 'threshold': np.float64

In [5]:
max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                             features=features,labels=labels,
                                             true_labels_for_points=true_labels_for_points,
                                             classification_objective='max_accuracy',
                                             fixed_depth=2,
                                             # min_support= 5
                                             # min_margin  = 10
                                             # tree_structure= 'Oblivious'
                                             )
max_accuracy_numerical_problem.solve()
max_accuracy_numerical_problem.export_cnf()
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)

Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('0'), 'threshold': np.float64(12.78)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('6'), 'threshold': np.float64(0.94)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('6'), 'threshold': np.float64(1.5750000000000002)}, {'type': 'leaf', 'label': np.int64(2)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(2)}, {'type': 'leaf', 'label': np.int64(0)}]
Min cost found:  11


In [6]:
max_accuracy_numerical_problem.sat_solution

[1,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -8,
 -9,
 -10,
 -11,
 -12,
 -13,
 -14,
 -15,
 -16,
 -17,
 -18,
 -19,
 20,
 -21,
 -22,
 -23,
 -24,
 -25,
 -26,
 -27,
 -28,
 -29,
 -30,
 -31,
 -32,
 33,
 -34,
 -35,
 -36,
 -37,
 -38,
 -39,
 -40,
 -41,
 -42,
 -43,
 -44,
 -45,
 -46,
 -47,
 -48,
 -49,
 -50,
 -51,
 -52,
 -53,
 -54,
 -55,
 -56,
 -57,
 -58,
 -59,
 -60,
 -61,
 -62,
 -63,
 -64,
 -65,
 -66,
 -67,
 -68,
 -69,
 -70,
 -71,
 -72,
 -73,
 -74,
 -75,
 -76,
 -77,
 -78,
 -79,
 -80,
 -81,
 -82,
 -83,
 -84,
 -85,
 -86,
 -87,
 -88,
 -89,
 -90,
 -91,
 -92,
 -93,
 -94,
 -95,
 -96,
 -97,
 -98,
 -99,
 -100,
 -101,
 -102,
 -103,
 -104,
 -105,
 -106,
 -107,
 -108,
 -109,
 -110,
 -111,
 -112,
 -113,
 -114,
 -115,
 -116,
 -117,
 -118,
 -119,
 -120,
 -121,
 -122,
 -123,
 -124,
 -125,
 -126,
 -127,
 -128,
 -129,
 -130,
 -131,
 -132,
 -133,
 -134,
 -135,
 -136,
 -137,
 -138,
 -139,
 -140,
 -141,
 -142,
 -143,
 -144,
 -145,
 -146,
 -147,
 -148,
 -149,
 -150,
 -151,
 -152,
 -153,
 -154,
 -155,
 -156,
 -157,
 -158,
 -159

In [7]:
min_height_numerical_problem.display_solution()


Solution of Literals
A Variables:
0 1 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 1
0 0 0 0 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0


S Variables:
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 1 0 0 0 0 0 1 1 0 0 0 0
1 0 0 1 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 

In [8]:
max_accuracy_numerical_problem.display_solution()


Solution of Literals
A Variables:
1 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0 0 0 0


S Variables:
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
1 1 1
1 0 1
1 0 1
0 0 0
1 0 0
1 0 0
1 0 0
0 0 0
1 0 0
0 0 1
1 0 1
1 0 1
0 0 0
0 0 0
0 0 0
1 0 0
1 0 1
0 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
0 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 1
1 0 1
1 0 1
1 0 0
1 0 0
1 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
0 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
0 0 1
0 0 1
0 0 1
1 0 1
1 1 1
1 1 1
1 1 1
1 1 1
0 1 1
0 1 1
0 1 1
0 1 1
0 1 1
0 1 1
1 1 1
0 

Model Classifier Tests - Numerical

In [9]:
# Classifier - sklearn Integration 

# Build model
model = SATreeClassifier(max_accuracy_numerical_problem.model)

# Test cases 0- uisng training set expecting 100%
X_test = dataset[5:160]
y_test = true_labels_for_points[5:160]

# To get the accuracy score
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

# To get the classification report
report = model.get_classification_report(X_test, y_test)
print("Classification Report:")
print(report)

# To get the confusion matrix
conf_matrix = model.get_confusion_matrix(X_test, y_test)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9290322580645162
Classification Report:
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        54
           1       0.98      0.86      0.92        71
           2       0.94      0.97      0.95        30

    accuracy                           0.93       155
   macro avg       0.93      0.94      0.93       155
weighted avg       0.94      0.93      0.93       155

Confusion Matrix:
[[54  0  0]
 [ 8 61  2]
 [ 0  1 29]]


K-Fold TESTS - NUMERICAL FOR MINIMUM Support 

In [10]:
k = 5
depth = 2 
minimum_support = 0
accuracies, mean_score = k_fold_tester(k=k, depth=depth, dataset=dataset, true_labels_for_points=true_labels_for_points, 
                                       labels=labels, features=features, min_support_level=minimum_support, 
                                       # complete_tree=False
                                       )

print(accuracies)
print(mean_score)

Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.9166666666666666
Fold complete. Accuracy = 0.8571428571428571
Fold complete. Accuracy = 0.7714285714285715
[0.88888889 0.88888889 0.91666667 0.85714286 0.77142857]
0.8646031746031746


Minimum Margin Testing - Numerical Dataset

In [11]:
k = 5
depth = 2 
minimum_margin = 4
accuracies, mean_score = k_fold_tester(k=k, depth=depth, dataset=dataset, true_labels_for_points=true_labels_for_points, 
                                       labels=labels, features=features, min_margin_level= minimum_margin,
                                       # complete_tree=False
                                       )

print(accuracies)
print(mean_score)

Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.8611111111111112
Fold complete. Accuracy = 0.8857142857142857
Fold complete. Accuracy = 0.7714285714285715
[0.88888889 0.88888889 0.86111111 0.88571429 0.77142857]
0.8592063492063492


Categorical Datasets Test

In [12]:
# Promoter data set
file_path = '../data/molecular+biology+promoter+gene+sequences/promoters.data'
label_index = 0
categorical_feature_index = 2  
numerical_indices = None

data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)

print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)


features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43'
 '44' '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56'] (57,)
Categorical Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43'
 '44' '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56'] (57,)
Numerical Features: [] (106, 0)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (106,)
Dataset:
 [['t' 'a' 'c' ... 'c' 'g' 't']
 ['t' 'g' 'c' ... 'c' 'a' 'a']
 ['g' 't' 'a' ... 'g' 'c' 

In [13]:
max_accuracy_categorical_problem = SATreeCraft(dataset=dataset,
                                           features=features,
                                           labels=labels,
                                           true_labels_for_points=true_labels_for_points,
                                           features_categorical=features_categorical,
                                           features_numerical=features_numerical,
                                           classification_objective= 'max_accuracy',
                                           fixed_depth=1,
                                           # min_support= 2,
                                           # tree_structure = 'Oblivious'
                                           )

max_accuracy_categorical_problem.solve()
max_accuracy_categorical_problem.export_cnf("dimacs/testThisFile.cnf")
print("Final Model: ", max_accuracy_categorical_problem.model)
print("Min cost found: ", max_accuracy_categorical_problem.min_cost)

Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('14'), 'threshold': [np.str_('a'), np.str_('c'), np.str_('g')]}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(0)}]
Min cost found:  21


Tree Classifier Tests Metrics - Sklearn

In [14]:
# Classifier - sklearn Integration 

# Build model
model = SATreeClassifier(max_accuracy_categorical_problem.model)

# Test cases 0- uisng training set expecting 100%
X_test = dataset
y_test = true_labels_for_points

# To get the accuracy score
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

# To get the classification report
report = model.get_classification_report(X_test, y_test)
print("Classification Report:")
print(report)

# To get the confusion matrix
conf_matrix = model.get_confusion_matrix(X_test, y_test)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.8018867924528302
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.81      0.80        53
           1       0.81      0.79      0.80        53

    accuracy                           0.80       106
   macro avg       0.80      0.80      0.80       106
weighted avg       0.80      0.80      0.80       106

Confusion Matrix:
[[43 10]
 [11 42]]


K-Fold Module test

In [15]:
k = 5
depth = 1

accuracies, mean_score = k_fold_tester(k, depth, dataset, true_labels_for_points, labels, features, features_categorical, features_numerical,
                                       # complete_tree= False
                                       )
                                       
print(accuracies)
print(mean_score)

Fold complete. Accuracy = 0.6818181818181818
Fold complete. Accuracy = 0.7142857142857143
Fold complete. Accuracy = 0.7619047619047619
Fold complete. Accuracy = 0.6666666666666666
Fold complete. Accuracy = 0.8095238095238095
[0.68181818 0.71428571 0.76190476 0.66666667 0.80952381]
0.7268398268398268


Adding Additional Constraints - Minimum Support

In [16]:
k = 5
depth = 1
minimum_support = 2
accuracies, mean_score = k_fold_tester(k, depth, dataset, true_labels_for_points, labels, features, features_categorical, features_numerical, True, minimum_support)

print(accuracies)
print(mean_score)

Fold complete. Accuracy = 0.8181818181818182
Fold complete. Accuracy = 0.6666666666666666
Fold complete. Accuracy = 0.7619047619047619
Fold complete. Accuracy = 0.6190476190476191
Fold complete. Accuracy = 0.8095238095238095
[0.81818182 0.66666667 0.76190476 0.61904762 0.80952381]
0.735064935064935


Own Toy sample

In [17]:
features = np.array(['0', '1'])
labels = np.array([0,1,2])
dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15,5],[15,7]])  # Dataset X
true_labels_for_points = np.array([0,0,1,1,2,2])

print("Features:", features, features.shape)
print("Labels:", labels, labels.shape)
print("True Labels for Points:", true_labels_for_points, true_labels_for_points.shape)
print("Dataset:\n", dataset,dataset.shape)

max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                             features=features,labels=labels,
                                             true_labels_for_points=true_labels_for_points,
                                             classification_objective='max_accuracy',
                                             fixed_depth=2,
                                             # min_support= 5
                                             # min_margin  = 10
                                             # tree_structure= 'Oblivious'
                                             )
max_accuracy_numerical_problem.solve()
max_accuracy_numerical_problem.export_cnf()
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)

Features: ['0' '1'] (2,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 1 1 2 2] (6,)
Dataset:
 [[ 1  1]
 [ 1  2]
 [ 7  7]
 [ 7  8]
 [15  5]
 [15  7]] (6, 2)
Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('0'), 'threshold': np.float64(11.0)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('1'), 'threshold': np.float64(3.5)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('1'), 'threshold': np.float64(7.5)}, {'type': 'leaf', 'label': np.int64(0)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(2)}, {'type': 'leaf', 'label': None}]
Min cost found:  0


# CLUSTERING

In [18]:
features = np.array(['0', '1'])
dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15,5],[15,6]])  # Dataset X
epsilon = 0 
k_clusters = 4
depth = 2

# cl_pairs = np.array([])
ml_pairs = np.array([])
cl_pairs = np.array([[2,3],[3,1]])
# # ml_pairs = np.array([[4,5],[0,1],[2,3]])

clustering_problem = SATreeCraft(dataset=dataset,
                                 features= features,
                                 k_clusters= k_clusters,
                                 #ml_pairs= ml_pairs,
                                 cl_pairs= cl_pairs,
                                 epsilon = epsilon,
                                 fixed_depth= depth
                                 )


In [19]:
clustering_problem.solve_loandra(loandra_path)
print(clustering_problem.cluster_assignments)
print(clustering_problem.cluster_diameters)

{0: [0, 1], 1: [2], 2: [3], 3: [4, 5]}
{0: np.float64(1.0), 1: 0, 2: 0, 3: np.float64(1.0)}


# Tests for results 

Numerical Datasets

In [20]:
file_path_to_test = '../data/data_banknote_authentication.txt'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3'] (4,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 ... 1 1 1] (1372,)
Dataset:
 [[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]] (1372, 4)


In [21]:
k = 5
depths = [2,3]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.92
Fold complete. Accuracy = 0.9054545454545454
Fold complete. Accuracy = 0.9087591240875912
Fold complete. Accuracy = 0.9014598540145985
Fold complete. Accuracy = 0.9452554744525548
Oblivious Depth: 2, Time Taken: 80.93 seconds
Accuracies: [0.92       0.90545455 0.90875912 0.90145985 0.94525547]
Mean Score: 0.9161857996018581

Fold complete. Accuracy = 0.9527272727272728
Fold complete. Accuracy = 0.9781818181818182
Fold complete. Accuracy = 0.9635036496350365
Fold complete. Accuracy = 0.9598540145985401
Fold complete. Accuracy = 0.9817518248175182
Oblivious Depth: 3, Time Taken: 189.03 seconds
Accuracies: [0.95272727 0.97818182 0.96350365 0.95985401 0.98175182]
Mean Score: 0.9672037159920371



In [22]:
file_path_to_test = '../data/breast+cancer+coimbra/dataR2.csv'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8'] (9,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1] (116,)
Dataset:
 [[ 48.          23.5         70.         ...   9.7024       7.99585
  417.114     ]
 [ 83.          20.69049454  92.         ...   5.429285     4.06405
  468.786     ]
 [ 82.          23.12467037  91.         ...  22.43204      9.27715
  554.697     ]
 ...
 [ 65.          32.05        97.         ...  22.54        10.33
  314.05      ]
 [ 72.          25.59        82.         ...  33.75         3.27
  392.46      ]
 [ 86.          27.18       138.         ...  14.11         4.35
   90.09      ]] (116, 9)


In [23]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.5416666666666666
Fold complete. Accuracy = 0.6956521739130435
Fold complete. Accuracy = 0.6956521739130435
Fold complete. Accuracy = 0.8260869565217391
Fold complete. Accuracy = 0.7391304347826086
Oblivious Depth: 2, Time Taken: 24.03 seconds
Accuracies: [0.54166667 0.69565217 0.69565217 0.82608696 0.73913043]
Mean Score: 0.6996376811594203



In [24]:
file_path_to_test = '../data/Cryotherapy.xlsx'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5'] (6,)
Labels: [0 1] (2,)
True Labels for Points: [0 1 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0
 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1
 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1] (90,)
Dataset:
 [[1.000e+00 3.500e+01 1.200e+01 5.000e+00 1.000e+00 1.000e+02]
 [1.000e+00 2.900e+01 7.000e+00 5.000e+00 1.000e+00 9.600e+01]
 [1.000e+00 5.000e+01 8.000e+00 1.000e+00 3.000e+00 1.320e+02]
 [1.000e+00 3.200e+01 1.175e+01 7.000e+00 3.000e+00 7.500e+02]
 [1.000e+00 6.700e+01 9.250e+00 1.000e+00 1.000e+00 4.200e+01]
 [1.000e+00 4.100e+01 8.000e+00 2.000e+00 2.000e+00 2.000e+01]
 [1.000e+00 3.600e+01 1.100e+01 2.000e+00 1.000e+00 8.000e+00]
 [1.000e+00 5.900e+01 3.500e+00 3.000e+00 3.000e+00 2.000e+01]
 [1.000e+00 2.000e+01 4.500e+00 1.200e+01 1.000e+00 6.000e+00]
 [2.000e+00 3.400e+01 1.125e+01 3.000e+00 3.000e+00 1.500e+02]
 [2.000e+00 2.100e+01 1.075e+01 5.000e+00 1.000e+00 3.500e+01]
 [2.000e+00 1.500e+01 6

In [25]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 1.0
Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.9444444444444444
Fold complete. Accuracy = 0.9444444444444444
Oblivious Depth: 2, Time Taken: 12.08 seconds
Accuracies: [1.         0.88888889 0.88888889 0.94444444 0.94444444]
Mean Score: 0.9333333333333333



In [26]:
file_path_to_test = '../data/Immunotherapy.xlsx'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6'] (7,)
Labels: [0 1] (2,)
True Labels for Points: [1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0
 1 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1
 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1] (90,)
Dataset:
 [[  1.    22.     2.25  14.     3.    51.    50.  ]
 [  1.    15.     3.     2.     3.   900.    70.  ]
 [  1.    16.    10.5    2.     1.   100.    25.  ]
 [  1.    27.     4.5    9.     3.    80.    30.  ]
 [  1.    20.     8.     6.     1.    45.     8.  ]
 [  1.    15.     5.     3.     3.    84.     7.  ]
 [  1.    35.     9.75   2.     2.     8.     6.  ]
 [  2.    28.     7.5    4.     1.     9.     2.  ]
 [  2.    19.     6.     2.     1.   225.     8.  ]
 [  2.    32.    12.     6.     3.    35.     5.  ]
 [  2.    33.     6.25   2.     1.    30.     3.  ]
 [  2.    17.     5.75  12.     3.    25.     7.  ]
 [  2.    15.     1.75   1.     2.    49.     7.  ]
 [  2.    15.     5.5   12.     1.  

In [27]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.7777777777777778
Fold complete. Accuracy = 0.7777777777777778
Fold complete. Accuracy = 0.8333333333333334
Fold complete. Accuracy = 0.7777777777777778
Fold complete. Accuracy = 0.7777777777777778
Oblivious Depth: 2, Time Taken: 13.37 seconds
Accuracies: [0.77777778 0.77777778 0.83333333 0.77777778 0.77777778]
Mean Score: 0.7888888888888889



In [28]:
file_path_to_test = '../data/ionosphere/ionosphere.data'
label_position = -1 
delimiter = ','
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33'] (34,)
Labels: [0 1] (2,)
True Labels for Points: [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (351,)
Dataset:
 [[ 1.       0.       0.99539 ... -0.54487  0.18

In [29]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.9154929577464789
Fold complete. Accuracy = 0.9142857142857143
Fold complete. Accuracy = 0.9142857142857143
Fold complete. Accuracy = 0.8571428571428571
Fold complete. Accuracy = 0.8714285714285714
Oblivious Depth: 2, Time Taken: 80.50 seconds
Accuracies: [0.91549296 0.91428571 0.91428571 0.85714286 0.87142857]
Mean Score: 0.8945271629778672



In [30]:
file_path_to_test = '../data/iris/iris.data'
label_position = -1 
delimiter = ','
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3'] (4,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] (150,)
Dataset:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 

In [31]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.9
Fold complete. Accuracy = 1.0
Fold complete. Accuracy = 0.9333333333333333
Fold complete. Accuracy = 0.9666666666666667
Fold complete. Accuracy = 0.9333333333333333
Oblivious Depth: 2, Time Taken: 13.99 seconds
Accuracies: [0.9        1.         0.93333333 0.96666667 0.93333333]
Mean Score: 0.9466666666666667



In [32]:
file_path_to_test = '../data/Data_User_Modeling_Dataset_Hamdi_Tolga_KAHRAMAN.xls'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4'] (5,)
Labels: [0 1 2 3] (4,)
True Labels for Points: [3 0 1 2 1 2 2 3 1 0 0 1 2 0 2 0 3 1 1 2 1 2 2 1 1 0 3 1 0 0 2 1 1 0 0 1 1
 1 3 2 1 0 2 2 3 2 2 0 0 2 1 2 1 0 2 1 2 2 0 1 1 2 2 1 2 3 3 2 1 2 2 0 3 2
 0 3 1 1 3 1 1 2 2 1 1 3 0 1 1 2 2 2 3 1 0 1 1 0 2 1 1 0 2 1 1 2 2 2 2 0 1
 1 0 0 2 2 3 0 2 0 1 1 1 2 0 0 0 1 1 2 1 2 3 0 2 2 1 1 2 1 3 2 2 1 2 0 1 3
 1 0 0 1 3 1 2 2 2 0 2 2 1 2 0 0 3 0 2 0 1 0 1 2 0 1 2 1 1 0 2 0 1 0 0 1 1
 1 0 2 1 0 2 0 2 0 2 1 3 1 2 3 3 2 3 1 0 1 2 2 3 0 2 2 0 2 2 1 1 0 2 1 1 2
 2 2 1 0 2 1 0 0 2 1 1 0 2 1 1 0 2 2 1 0 2 1 2 0 2 1 0 2 2 2 1 0 2 0 2 0] (258,)
Dataset:
 [[0.   0.   0.   0.   0.  ]
 [0.08 0.08 0.1  0.24 0.9 ]
 [0.06 0.06 0.05 0.25 0.33]
 ...
 [0.54 0.82 0.71 0.29 0.77]
 [0.5  0.75 0.81 0.61 0.26]
 [0.66 0.9  0.76 0.87 0.74]] (258, 5)


In [33]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.8846153846153846
Fold complete. Accuracy = 0.8846153846153846
Fold complete. Accuracy = 0.8076923076923077
Fold complete. Accuracy = 0.8431372549019608
Fold complete. Accuracy = 0.803921568627451
Oblivious Depth: 2, Time Taken: 25.16 seconds
Accuracies: [0.88461538 0.88461538 0.80769231 0.84313725 0.80392157]
Mean Score: 0.8447963800904977



In [34]:
file_path_to_test = '../data/vertebral+column/verbex.data'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5'] (6,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (310,)
Dataset:
 [[ 63.0278175   22.55258597  39.60911701  40.47523153  98.67291675
   -0.25439999]
 [ 39.05695098  10.06099147  25.01537822  28.99595951 114.4054254
    4.56425864]
 [ 68.83202098  22.21848205  50.09219357  46.61353893 105.9851355
   -3.53031731]
 ...
 [ 61.44659663  2

In [35]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.8548387096774194
Fold complete. Accuracy = 0.8064516129032258
Fold complete. Accuracy = 0.7419354838709677
Fold complete. Accuracy = 0.7903225806451613
Fold complete. Accuracy = 0.7741935483870968
Oblivious Depth: 2, Time Taken: 36.39 seconds
Accuracies: [0.85483871 0.80645161 0.74193548 0.79032258 0.77419355]
Mean Score: 0.7935483870967742



In [36]:
file_path_to_test = '../data/wine/wine.data'
delimiter = ','
label_position = 0 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'] (13,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] (178,)
Dataset:
 [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] (178, 13)


In [37]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.7777777777777778
Fold complete. Accuracy = 0.8611111111111112
Fold complete. Accuracy = 0.8333333333333334
Fold complete. Accuracy = 0.7428571428571429
Fold complete. Accuracy = 0.8857142857142857
Oblivious Depth: 2, Time Taken: 20.98 seconds
Accuracies: [0.77777778 0.86111111 0.83333333 0.74285714 0.88571429]
Mean Score: 0.8201587301587303



In [38]:
file_path_to_test = '../data/monk+s+problems/monks-2.train'  # Update this to the path of your data file
delimiter = ' '
label_position = 0 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position, custom_exclude=[-1])
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5'] (6,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 1 0 1 1 0
 1 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0
 0 0 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0 1 0 0
 0 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1
 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0] (169,)
Dataset:
 [[1. 1. 1. 1. 2. 2.]
 [1. 1. 1. 1. 4. 1.]
 [1. 1. 1. 2. 1. 1.]
 ...
 [3. 3. 2. 3. 1. 1.]
 [3. 3. 2. 3. 2. 1.]
 [3. 3. 2. 3. 4. 2.]] (169, 6)


In [39]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0,
                                                complete_tree= False)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.4117647058823529
Fold complete. Accuracy = 0.5882352941176471
Fold complete. Accuracy = 0.4411764705882353
Fold complete. Accuracy = 0.5882352941176471
Fold complete. Accuracy = 0.6060606060606061
Oblivious Depth: 2, Time Taken: 19.74 seconds
Accuracies: [0.41176471 0.58823529 0.44117647 0.58823529 0.60606061]
Mean Score: 0.5270944741532977



Max height Problem - Numerical

In [40]:
max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                             features=features,labels=labels,
                                             true_labels_for_points=true_labels_for_points,
                                             classification_objective='max_accuracy',
                                             fixed_depth=3,
                                             # min_support= 5
                                             # min_margin  = 10
                                             # tree_structure= 'Oblivious'
                                             )
max_accuracy_numerical_problem.solve_loandra(loandra_path= loandra_path)
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)

Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('2'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('4'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('4'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [7, 8], 'feature': np.str_('5'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [9, 10], 'feature': np.str_('5'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [11, 12], 'feature': np.str_('5'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [13, 14], 'feature': np.str_('5'), 'threshold': np.float64(1.5)}, {'type': 'leaf', 'label': np.int64(0)}, {'type': 'leaf', 'label': np.int64(0)}, {'type': 'leaf', 'label': np.int64(0)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(0)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(0)}, {'type': 'leaf

Min Height Problem - Numerical

In [41]:
min_height_numerical_problem = SATreeCraft(dataset=dataset,features=features,labels=labels,true_labels_for_points=true_labels_for_points)
min_height_numerical_problem.solve_loandra(loandra_path)
print("Final Model: ", min_height_numerical_problem.model)
print("min depth found: ", min_height_numerical_problem.min_depth)

no solution at depth 1
no solution at depth 2
no solution at depth 3
no solution at depth 4
no solution at depth 5
Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('2'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('4'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('4'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [7, 8], 'feature': np.str_('1'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [9, 10], 'feature': np.str_('1'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [11, 12], 'feature': np.str_('1'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [13, 14], 'feature': np.str_('1'), 'threshold': np.float64(1.5)}, {'type': 'branching', 'children': [15, 16], 'feature': np.str_('3'), 'threshold': np.float64(2.5)}, {'type': 'branching', 'children': [17, 18], 'feature': np.str_('3'), 'threshold

K-fold tests accuracies

In [42]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()

# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features,
                                                min_support_level= 0)
# Capture the end time
end_time = time.time()

# Calculate the duration
duration = end_time - start_time

# Print or log the results including the time taken
print(f"Depth: {depth}, Min Support: {minimum_support}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.5882352941176471
Fold complete. Accuracy = 0.6176470588235294
Fold complete. Accuracy = 0.6176470588235294
Fold complete. Accuracy = 0.7058823529411765
Fold complete. Accuracy = 0.5454545454545454
Depth: 2, Min Support: 2, Time Taken: 21.58 seconds
Accuracies: [0.58823529 0.61764706 0.61764706 0.70588235 0.54545455]
Mean Score: 0.6149732620320856



Categorical Datasets

In [43]:
# Example usage:
file_path = '../data/credit+approval/crx.data'
label_index = -1
categorical_feature_index = None  
numerical_indices = np.array([1, 2, 7, 10, 13,14]) 

data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)

# Accessing the processed data
print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14'] (15,)
Categorical Features: ['0' '3' '4' '5' '6' '8' '9' '11' '12'] (9,)
Numerical Features: ['1' '2' '7' '10' '13' '14'] (6,)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 

In [44]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()
# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical,
                                                min_support_level=0, complete_tree= False)
# Capture the end time
end_time = time.time()
# Calculate the duration
duration = end_time - start_time
# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.8320610687022901
Fold complete. Accuracy = 0.8625954198473282
Fold complete. Accuracy = 0.7786259541984732
Fold complete. Accuracy = 0.8923076923076924
Fold complete. Accuracy = 0.9076923076923077
Oblivious Depth: 2, Time Taken: 113.56 seconds
Accuracies: [0.83206107 0.86259542 0.77862595 0.89230769 0.90769231]
Mean Score: 0.8546564885496183



In [45]:
# Promoter data set
file_path = '../data/molecular+biology+promoter+gene+sequences/promoters.data'
label_index = 0
categorical_feature_index = 2  
numerical_indices = None
data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)
print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43'
 '44' '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56'] (57,)
Categorical Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43'
 '44' '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56'] (57,)
Numerical Features: [] (106, 0)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (106,)
Dataset:
 [['t' 'a' 'c' ... 'c' 'g' 't']
 ['t' 'g' 'c' ... 'c' 'a' 'a']
 ['g' 't' 'a' ... 'g' 'c' 

In [46]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()
# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical,
                                                min_support_level=0, complete_tree= False)
# Capture the end time
end_time = time.time()
# Calculate the duration
duration = end_time - start_time
# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.7272727272727273
Fold complete. Accuracy = 0.6190476190476191
Fold complete. Accuracy = 0.8095238095238095
Fold complete. Accuracy = 0.8095238095238095
Fold complete. Accuracy = 0.8571428571428571
Oblivious Depth: 2, Time Taken: 233.73 seconds
Accuracies: [0.72727273 0.61904762 0.80952381 0.80952381 0.85714286]
Mean Score: 0.7645021645021646



In [47]:
file_path = '../data/hiv+1+protease+cleavage/746Data.txt'
label_index = 1
categorical_feature_index = 0  # The features are a string at the third element
numerical_indices = None
data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)
# Accessing the processed data
print("Features:", data_loader.features)
print("Categorical Features:", data_loader.features_categorical)
print("Numerical Features:", data_loader.features_numerical)
print("Labels:", data_loader.labels)
print("True Labels for Points:", data_loader.true_labels_for_points)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

dataset = dataset[3::4]
true_labels_for_points = true_labels_for_points[3::4]

Features: ['0' '1' '2' '3' '4' '5' '6' '7']
Categorical Features: ['0' '1' '2' '3' '4' '5' '6' '7']
Numerical Features: []
Labels: [0 1]
True Labels for Points: [0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 1 1 0 1 0
 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1
 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1
 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1
 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1

In [48]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()
# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical,
                                                min_support_level=0, complete_tree= False)
# Capture the end time
end_time = time.time()
# Calculate the duration
duration = end_time - start_time
# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.8421052631578947
Fold complete. Accuracy = 0.6756756756756757
Fold complete. Accuracy = 0.7837837837837838
Fold complete. Accuracy = 0.8378378378378378
Fold complete. Accuracy = 0.7567567567567568
Oblivious Depth: 2, Time Taken: 28.08 seconds
Accuracies: [0.84210526 0.67567568 0.78378378 0.83783784 0.75675676]
Mean Score: 0.7792318634423898



In [49]:
file_path = '../data/soybean+large/soybean-large.data'
label_index = 0
categorical_feature_index = None  # The features are a string at the third element
numerical_indices = None

data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)

# Accessing the processed data
print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34'] (35,)
Categorical Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34'] (35,)
Numerical Features: [] (0,)
Labels: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)
True Labels for Points: [ 0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  2  2  2  2
  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5
  5  5  5  5  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7
  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7
  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9
  9  9 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 

In [50]:
k = 5
depth = 2

# Capture the start time
start_time = time.time()
# Execute the k-fold tester
accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                k=k, depth=depth, dataset=dataset,
                                                true_labels_for_points=true_labels_for_points,
                                                labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical,
                                                min_support_level=0, complete_tree= False)
# Capture the end time
end_time = time.time()
# Calculate the duration
duration = end_time - start_time
# Print or log the results including the time taken
print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
print(f"Accuracies: {accuracies}")
print(f"Mean Score: {mean_score}\n")

Fold complete. Accuracy = 0.4074074074074074
Fold complete. Accuracy = 0.4339622641509434
Fold complete. Accuracy = 0.41509433962264153
Fold complete. Accuracy = 0.4528301886792453
Fold complete. Accuracy = 0.33962264150943394
Oblivious Depth: 2, Time Taken: 115.55 seconds
Accuracies: [0.40740741 0.43396226 0.41509434 0.45283019 0.33962264]
Mean Score: 0.4097833682739343



In [51]:
file_path = '../data/hiv+1+protease+cleavage/746Data.txt'
label_index = 1
categorical_feature_index = 0  # The features are a string at the third element
numerical_indices = None
data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)
# Accessing the processed data
print("Features:", data_loader.features)
print("Categorical Features:", data_loader.features_categorical)
print("Numerical Features:", data_loader.features_numerical)
print("Labels:", data_loader.labels)
print("True Labels for Points:", data_loader.true_labels_for_points)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7']
Categorical Features: ['0' '1' '2' '3' '4' '5' '6' '7']
Numerical Features: []
Labels: [0 1]
True Labels for Points: [0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 1 1 0 1 0
 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1
 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1
 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1
 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1

Max Accuracy Categorical

In [52]:
max_accuracy_categorical_problem = SATreeCraft(dataset=dataset,
                                           features=features,
                                           labels=labels,
                                           true_labels_for_points=true_labels_for_points,
                                           features_categorical=features_categorical,
                                           features_numerical=features_numerical,
                                           classification_objective= 'max_accuracy',
                                           fixed_depth=1,
                                           # min_support= 2,
                                           # tree_structure = 'Oblivious'
                                           )

max_accuracy_categorical_problem.solve_loandra(loandra_path)
print("Final Model: ", max_accuracy_categorical_problem.model)
print("Min cost found: ", max_accuracy_categorical_problem.min_cost)

Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('3'), 'threshold': [np.str_('A'), np.str_('C'), np.str_('D'), np.str_('E'), np.str_('G'), np.str_('H'), np.str_('I'), np.str_('K'), np.str_('N'), np.str_('P'), np.str_('Q'), np.str_('R'), np.str_('T'), np.str_('V')]}, {'type': 'leaf', 'label': np.int64(0)}, {'type': 'leaf', 'label': np.int64(1)}]
Min cost found:  142


Min Height Categorical

In [53]:
min_height_categorical_problem = SATreeCraft(dataset=dataset,
                                           features=features,
                                           labels=labels,
                                           true_labels_for_points=true_labels_for_points,
                                           features_categorical=features_categorical,
                                           features_numerical=features_numerical)
min_height_categorical_problem.solve()
min_height_categorical_problem.export_cnf()
print("Final Model: ", min_height_categorical_problem.model)
print("min depth found: ", min_height_categorical_problem.min_depth)

No solution at depth:  1
No solution at depth:  2
No solution at depth:  3
No solution at depth:  4
No solution at depth:  5


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.444112 to fit


Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('6'), 'threshold': [np.str_('A'), np.str_('E'), np.str_('F'), np.str_('G'), np.str_('I'), np.str_('R'), np.str_('S'), np.str_('T'), np.str_('V')]}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('7'), 'threshold': [np.str_('A'), np.str_('I'), np.str_('M'), np.str_('N'), np.str_('P'), np.str_('S'), np.str_('T'), np.str_('V'), np.str_('W'), np.str_('Y')]}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('7'), 'threshold': [np.str_('A'), np.str_('C'), np.str_('E'), np.str_('F'), np.str_('G'), np.str_('I'), np.str_('K'), np.str_('M'), np.str_('N'), np.str_('R'), np.str_('V'), np.str_('W'), np.str_('Y')]}, {'type': 'branching', 'children': [7, 8], 'feature': np.str_('5'), 'threshold': [np.str_('A'), np.str_('C'), np.str_('D'), np.str_('F'), np.str_('G'), np.str_('I'), np.str_('K'), np.str_('M'), np.str_('N'), np.str_('Q'), np.str_('R'), np.str_('T'), np.str_('W')]}, {'type': 'branching', '