# DataLoader

In [1]:
import numpy as np

from satree.utils import TreeDataLoaderBinaryNumerical, k_fold_tester # Dataloader and K-fold mechanism
from satree.SATreeCraft import SATreeCraft # Tree solver framework

In [2]:
file_path_to_test = '../data/wine/wine.data'
delimiter = ','
label_position = 0 

data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)

print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'] (13,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] (178,)
Dataset:
 [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] (178, 13)


# Classification

In [3]:
min_height_numerical_problem = SATreeCraft(dataset=dataset,features=features,labels=labels,true_labels_for_points=true_labels_for_points)
min_height_numerical_problem.solve()
#min_height_numerical_problem.export_cnf_min_height("dimacs/testPerfectHeight.cnf")
print("Final Model: ", min_height_numerical_problem.model)
print("min depth found: ", min_height_numerical_problem.min_depth)

no solution at depth 1
no solution at depth 2
no solution at depth 3
Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('1'), 'threshold': np.float64(2.375)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('12'), 'threshold': np.float64(775.0)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('12'), 'threshold': np.float64(517.5)}, {'type': 'branching', 'children': [7, 8], 'feature': np.str_('0'), 'threshold': np.float64(13.35)}, {'type': 'branching', 'children': [9, 10], 'feature': np.str_('0'), 'threshold': np.float64(13.01)}, {'type': 'branching', 'children': [11, 12], 'feature': np.str_('0'), 'threshold': np.float64(13.04)}, {'type': 'branching', 'children': [13, 14], 'feature': np.str_('0'), 'threshold': np.float64(12.905000000000001)}, {'type': 'branching', 'children': [15, 16], 'feature': np.str_('11'), 'threshold': np.float64(1.585)}, {'type': 'branching', 'children': [17, 18], 'feature': np.str_('11'), 'threshold': np.float64

In [4]:
max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                             features=features,labels=labels,
                                             true_labels_for_points=true_labels_for_points,
                                             classification_objective='max_accuracy',
                                             fixed_depth=2,
                                             # min_support= 5
                                             min_margin  = 4,
                                             tree_structure= 'Oblivious'
                                             )
max_accuracy_numerical_problem.solve()
max_accuracy_numerical_problem.export_cnf()
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)

Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('6'), 'threshold': np.float64(2.035)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('9'), 'threshold': np.float64(3.8449999999999998)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('9'), 'threshold': np.float64(3.46)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(2)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(0)}]
Min cost found:  11


# LOANDRA

In [5]:
# Path to the loandra executable (recommended to use for faster solving). To install, follow: https://github.com/jezberg/loandra
loandra_path = "/home/dvm/projects/sat/loandra"  # Change as needed

In [6]:
max_accuracy_numerical_problem.solve_loandra(loandra_path)
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)

Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('6'), 'threshold': np.float64(2.1799999999999997)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('9'), 'threshold': np.float64(3.8449999999999998)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('9'), 'threshold': np.float64(3.46)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(2)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(0)}]
Min cost found:  11


# SKLEARN Integration

In [7]:
k = 5
depth = 2 
minimum_support = 0
accuracies, mean_score = k_fold_tester(k, depth, dataset, true_labels_for_points, labels, features, 
                                       # complete_tree= False
                                       )
                                       
print(accuracies)
print(mean_score)

Fold complete. Accuracy = 0.9166666666666666
Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.8888888888888888
Fold complete. Accuracy = 0.8285714285714286
Fold complete. Accuracy = 0.9428571428571428
[0.91666667 0.88888889 0.88888889 0.82857143 0.94285714]
0.8931746031746032


# Clustering

In [8]:
features = np.array(['0', '1'])
dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15,5],[15,6]])  # Dataset X
epsilon = 1 
k_clusters = 3
depth = 2

# # ml_pairs = np.array([[4,5],[0,1],[2,3]])
# cl_pairs = np.array([])

ml_pairs = np.array([])
cl_pairs = np.array([[2,3],[3,1]])


clustering_problem = max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                                                  features= features,
                                                                  k_clusters= k_clusters,
                                                                  ml_pairs= ml_pairs,
                                                                  cl_pairs= cl_pairs,
                                                                  epsilon = epsilon,
                                                                  fixed_depth= depth
                                                                  )

clustering_problem.solve_loandra(loandra_path)
print(clustering_problem.cluster_assignments)
print(clustering_problem.cluster_diameters)

{0: [0, 1], 1: [2, 4, 5], 2: [3]}
{0: np.float64(1.0), 1: np.float64(8.246211251235321), 2: 0}


In [9]:
features = np.array(['0'])
dataset = np.array([[0], [2], [3], [9], [11], [19]])  # Dataset X
epsilon = 0
k_clusters = 2
depth = 3

ml_pairs = np.array([[0,3]])
cl_pairs = np.array([])
clustering_obj = 'max_diamete'


clustering_problem = SATreeCraft(dataset=dataset,
                                 features= features,
                                 k_clusters= k_clusters,
                                 ml_pairs= ml_pairs,
                                 cl_pairs= cl_pairs,
                                 epsilon = epsilon,
                                 fixed_depth= depth,
                                 clustering_objective=clustering_obj,
                                 smart_pairs= True
                                 )
clustering_problem.solve()
#loandra_path = '/Users/harisrasul/Desktop/loandra'
#clustering_problem.solve_loandra(loandra_path)
print(clustering_problem.cluster_assignments)
print(clustering_problem.cluster_diameters)


{0: [0, 1, 2, 3, 4], 1: [5]}
{0: np.float64(11.0), 1: 0}


In [10]:
clustering_problem.min_cost

In [11]:
clustering_problem.sat_solution

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 -16,
 17,
 -18,
 -19,
 -20,
 -21,
 -22,
 -23,
 24,
 -25,
 -26,
 -27,
 -28,
 -29,
 -30,
 31,
 -32,
 -33,
 -34,
 -35,
 -36,
 -37,
 38,
 -39,
 -40,
 -41,
 -42,
 -43,
 -44,
 -45,
 -46,
 -47,
 -48,
 -49,
 50,
 -51,
 -52,
 -53,
 -54,
 -55,
 -56,
 -57,
 -58,
 -59,
 -60,
 61,
 -62,
 -63,
 -64,
 -65,
 -66,
 -67,
 -68,
 -69,
 -70,
 71,
 -72,
 -73,
 -74,
 -75,
 -76,
 -77,
 -78,
 79,
 -80,
 -81,
 -82,
 -83,
 -84,
 -85,
 -86,
 87,
 -88,
 -89,
 -90,
 -91,
 -92,
 -93,
 -94,
 -95,
 -96,
 97,
 -98,
 -99,
 -100,
 -101,
 -102,
 -103,
 -104,
 -105,
 -106,
 -107,
 -108,
 -109,
 -110,
 -111,
 112,
 -113,
 -114,
 -115,
 -116,
 -117,
 -118,
 -119,
 -120,
 -121,
 -122,
 -123,
 124,
 -125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 -135,
 -136,
 -137,
 138,
 139,
 140,
 141,
 142,
 -143,
 -144,
 -145,
 -146,
 -147,
 -148,
 -149]