In [9]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pandas as pd
import openpyxl
from sklearn.preprocessing import LabelEncoder

from satree.utils import * # Dataloader and K-fold mechanism
from satree.SATreeCraft import * # Tree solver framework
from satree.SATreeClassifier import *

Numerical Tests

In [2]:
from satree.utils import *

file_path_to_test = '../data/wine/wine.data'
delimiter = ','
label_position = 0 

data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)



print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)


features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'] (13,)
Labels: [0 1 2] (3,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] (178,)
Dataset:
 [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] (178, 13)


Min-Height Problem 100% Training Accuracy

In [3]:
min_height_numerical_problem = SATreeCraft(dataset=dataset,features=features,labels=labels,true_labels_for_points=true_labels_for_points)
min_height_numerical_problem.solve()
#min_height_numerical_problem.export_cnf_min_height("dimacs/testPerfectHeight.cnf")
print("Final Model: ", min_height_numerical_problem.model)
print("min depth found: ", min_height_numerical_problem.min_depth)

no solution at depth 1
no solution at depth 2
no solution at depth 3
Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('1'), 'threshold': np.float64(2.375)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('12'), 'threshold': np.float64(775.0)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('12'), 'threshold': np.float64(517.5)}, {'type': 'branching', 'children': [7, 8], 'feature': np.str_('0'), 'threshold': np.float64(13.35)}, {'type': 'branching', 'children': [9, 10], 'feature': np.str_('0'), 'threshold': np.float64(13.01)}, {'type': 'branching', 'children': [11, 12], 'feature': np.str_('0'), 'threshold': np.float64(13.04)}, {'type': 'branching', 'children': [13, 14], 'feature': np.str_('0'), 'threshold': np.float64(12.905000000000001)}, {'type': 'branching', 'children': [15, 16], 'feature': np.str_('11'), 'threshold': np.float64(1.585)}, {'type': 'branching', 'children': [17, 18], 'feature': np.str_('11'), 'threshold': np.float64

In [6]:
max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                             features=features,labels=labels,
                                             true_labels_for_points=true_labels_for_points,
                                             classification_objective='max_accuracy',
                                             fixed_depth=2,
                                             # min_support= 5
                                             # min_margin  = 10
                                             # tree_structure= 'Oblivious'
                                             )
max_accuracy_numerical_problem.solve()
max_accuracy_numerical_problem.export_cnf()
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)

Hi
Final Model:  [{'type': 'branching', 'children': [1, 2], 'feature': np.str_('0'), 'threshold': np.float64(12.78)}, {'type': 'branching', 'children': [3, 4], 'feature': np.str_('6'), 'threshold': np.float64(0.94)}, {'type': 'branching', 'children': [5, 6], 'feature': np.str_('6'), 'threshold': np.float64(1.5750000000000002)}, {'type': 'leaf', 'label': np.int64(2)}, {'type': 'leaf', 'label': np.int64(1)}, {'type': 'leaf', 'label': np.int64(2)}, {'type': 'leaf', 'label': np.int64(0)}]
Min cost found:  11


In [5]:
max_accuracy_numerical_problem.sat_solution

[1,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -8,
 -9,
 -10,
 -11,
 -12,
 -13,
 -14,
 -15,
 -16,
 -17,
 -18,
 -19,
 20,
 -21,
 -22,
 -23,
 -24,
 -25,
 -26,
 -27,
 -28,
 -29,
 -30,
 -31,
 -32,
 33,
 -34,
 -35,
 -36,
 -37,
 -38,
 -39,
 -40,
 -41,
 -42,
 -43,
 -44,
 -45,
 -46,
 -47,
 -48,
 -49,
 -50,
 -51,
 -52,
 -53,
 -54,
 -55,
 -56,
 -57,
 -58,
 -59,
 -60,
 -61,
 -62,
 -63,
 -64,
 -65,
 -66,
 -67,
 -68,
 -69,
 -70,
 -71,
 -72,
 -73,
 -74,
 -75,
 -76,
 -77,
 -78,
 -79,
 -80,
 -81,
 -82,
 -83,
 -84,
 -85,
 -86,
 -87,
 -88,
 -89,
 -90,
 -91,
 -92,
 -93,
 -94,
 -95,
 -96,
 -97,
 -98,
 -99,
 -100,
 -101,
 -102,
 -103,
 -104,
 -105,
 -106,
 -107,
 -108,
 -109,
 -110,
 -111,
 -112,
 -113,
 -114,
 -115,
 -116,
 -117,
 -118,
 -119,
 -120,
 -121,
 -122,
 -123,
 -124,
 -125,
 -126,
 -127,
 -128,
 -129,
 -130,
 -131,
 -132,
 -133,
 -134,
 -135,
 -136,
 -137,
 -138,
 -139,
 -140,
 -141,
 -142,
 -143,
 -144,
 -145,
 -146,
 -147,
 -148,
 -149,
 -150,
 -151,
 -152,
 -153,
 -154,
 -155,
 -156,
 -157,
 -158,
 -159

In [6]:
min_height_numerical_problem.display_solution()


Solution of Literals
A Variables:
0 1 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 1
0 0 0 0 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0
0 0 0 0 0 0 0 0 0 0 0 1 0


S Variables:
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 1 0 0 0 0 0 1 1 0 0 0 0
1 0 0 1 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
1 0 0 0 0 0 0 0 0 1 

In [7]:
max_accuracy_numerical_problem.display_solution()


Solution of Literals
A Variables:
1 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0 0 0 0


S Variables:
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
1 1 1
1 0 1
1 0 1
0 0 0
1 0 0
1 0 0
1 0 0
0 0 0
1 0 0
0 0 1
1 0 1
1 0 1
0 0 0
0 0 0
0 0 0
1 0 0
1 0 1
0 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
0 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 1
1 0 1
1 0 1
1 0 0
1 0 0
1 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 1
1 0 0
1 0 0
1 0 0
1 0 0
0 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
0 0 1
0 0 1
0 0 1
1 0 1
1 1 1
1 1 1
1 1 1
1 1 1
0 1 1
0 1 1
0 1 1
0 1 1
0 1 1
0 1 1
1 1 1
0 

Model Classifier Tests - Numerical

In [8]:
# Classifier - sklearn Integration 

# Build model
model = SATreeClassifier(max_accuracy_numerical_problem.model)

# Test cases 0- uisng training set expecting 100%
X_test = dataset[5:160]
y_test = true_labels_for_points[5:160]

# To get the accuracy score
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

# To get the classification report
report = model.get_classification_report(X_test, y_test)
print("Classification Report:")
print(report)

# To get the confusion matrix
conf_matrix = model.get_confusion_matrix(X_test, y_test)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9290322580645162
Classification Report:
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        54
           1       0.98      0.86      0.92        71
           2       0.94      0.97      0.95        30

    accuracy                           0.93       155
   macro avg       0.93      0.94      0.93       155
weighted avg       0.94      0.93      0.93       155

Confusion Matrix:
[[54  0  0]
 [ 8 61  2]
 [ 0  1 29]]


K-Fold TESTS - NUMERICAL FOR MINIMUM Support 

In [13]:
k = 5
depth = 2 
minimum_support = 0
accuracies, mean_score = k_fold_tester(k=k, depth=depth, dataset=dataset, true_labels_for_points=true_labels_for_points, 
                                       labels=labels, features=features, min_support_level=minimum_support, 
                                       # complete_tree=False
                                       )

print(accuracies)
print(mean_score)

Hi
self dooot minmargin 1
Fold complete. Accuracy = 0.8888888888888888
Hi
self dooot minmargin 1
Fold complete. Accuracy = 0.9722222222222222
Hi
self dooot minmargin 1
Fold complete. Accuracy = 0.8888888888888888
Hi
self dooot minmargin 1
Fold complete. Accuracy = 0.9142857142857143
Hi
self dooot minmargin 1
Fold complete. Accuracy = 0.9142857142857143
[0.88888889 0.97222222 0.88888889 0.91428571 0.91428571]
0.9157142857142857


Minimum Margin Testing - Numerical Dataset

In [12]:
k = 5
depth = 2 
minimum_margin = 4
accuracies, mean_score = k_fold_tester(k=k, depth=depth, dataset=dataset, true_labels_for_points=true_labels_for_points, 
                                       labels=labels, features=features, min_margin_level= minimum_margin,
                                       # complete_tree=False
                                       )

print(accuracies)
print(mean_score)

Hi
self dooot minmargin 4
HI2222
Fold complete. Accuracy = 0.9444444444444444
Hi
self dooot minmargin 4
HI2222
Fold complete. Accuracy = 0.8333333333333334
Hi
self dooot minmargin 4
HI2222
Fold complete. Accuracy = 0.9166666666666666
Hi
self dooot minmargin 4
HI2222
Fold complete. Accuracy = 0.8285714285714286
Hi
self dooot minmargin 4
HI2222
Fold complete. Accuracy = 0.8571428571428571
[0.94444444 0.83333333 0.91666667 0.82857143 0.85714286]
0.8760317460317459


Categorical Datasets Test

In [13]:
# Promoter data set
file_path = '../data/molecular+biology+promoter+gene+sequences/promoters.data'
label_index = 0
categorical_feature_index = 2  
numerical_indices = None

data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)

print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)


features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43'
 '44' '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56'] (57,)
Categorical Features: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43'
 '44' '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56'] (57,)
Numerical Features: [] (106, 0)
Labels: [0 1] (2,)
True Labels for Points: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] (106,)
Dataset:
 [['t' 'a' 'c' ... 'c' 'g' 't']
 ['t' 'g' 'c' ... 'c' 'a' 'a']
 ['g' 't' 'a' ... 'g' 'c' 

In [14]:
min_height_categorical_problem = SATreeCraft(dataset=dataset,
                                           features=features,
                                           labels=labels,
                                           true_labels_for_points=true_labels_for_points,
                                           features_categorical=features_categorical,
                                           features_numerical=features_numerical)
min_height_categorical_problem.solve()
min_height_categorical_problem.export_cnf()
print("Final Model: ", min_height_categorical_problem.model)
print("min depth found: ", min_height_categorical_problem.min_depth)

No solution at depth:  1
No solution at depth:  2
No solution at depth:  3


error: Caught keyboard interrupt

In [ ]:
max_accuracy_categorical_problem = SATreeCraft(dataset=dataset,
                                           features=features,
                                           labels=labels,
                                           true_labels_for_points=true_labels_for_points,
                                           features_categorical=features_categorical,
                                           features_numerical=features_numerical,
                                           classification_objective= 'max_accuracy',
                                           fixed_depth=2,
                                           # min_support= 2,
                                           # tree_structure = 'Oblivious'
                                           )

max_accuracy_categorical_problem.solve()
max_accuracy_categorical_problem.export_cnf("dimacs/testThisFile.cnf")
print("Final Model: ", max_accuracy_categorical_problem.model)
print("Min cost found: ", max_accuracy_categorical_problem.min_cost)

Tree Classifier Tests Metrics - Sklearn

In [ ]:
# Classifier - sklearn Integration 

# Build model
model = SATreeClassifier(max_accuracy_categorical_problem.model)

# Test cases 0- uisng training set expecting 100%
X_test = dataset
y_test = true_labels_for_points

# To get the accuracy score
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

# To get the classification report
report = model.get_classification_report(X_test, y_test)
print("Classification Report:")
print(report)

# To get the confusion matrix
conf_matrix = model.get_confusion_matrix(X_test, y_test)
print("Confusion Matrix:")
print(conf_matrix)

K-Fold Module test

In [ ]:
k = 5
depth = 2 
minimum_support = 0
accuracies, mean_score = k_fold_tester(k, depth, dataset, true_labels_for_points, labels, features, features_categorical, features_numerical, 
                                       # complete_tree= False
                                       )
                                       
print(accuracies)
print(mean_score)

Adding Additional Constraints - Minimum Support

In [ ]:
k = 5
depth = 2 
minimum_support = 2
accuracies, mean_score = k_fold_tester(k, depth, dataset, true_labels_for_points, labels, features, features_categorical, features_numerical, True, minimum_support)

print(accuracies)
print(mean_score)

Own Toy sample

In [ ]:
features = np.array(['0', '1'])
labels = np.array([0,1,2])
dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15,5],[15,7]])  # Dataset X
true_labels_for_points = np.array([0,0,1,1,2,2])

print("Features:", features, features.shape)
print("Labels:", labels, labels.shape)
print("True Labels for Points:", true_labels_for_points, true_labels_for_points.shape)
print("Dataset:\n", dataset,dataset.shape)

max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                             features=features,labels=labels,
                                             true_labels_for_points=true_labels_for_points,
                                             classification_objective='max_accuracy',
                                             fixed_depth=2,
                                             # min_support= 5
                                             # min_margin  = 10
                                             # tree_structure= 'Oblivious'
                                             )
max_accuracy_numerical_problem.solve()
max_accuracy_numerical_problem.export_cnf()
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)



# CLUSTERING

In [ ]:
import numpy as np
import pandas as pd
import openpyxl
from sklearn.preprocessing import LabelEncoder

from satree.utils import * # Dataloader and K-fold mechanism
from satree.SATreeCraft import * # Tree solver framework
from satree.SATreeClassifier import *

In [ ]:
features = np.array(['0', '1'])
dataset = np.array([[1, 1], [1, 2], [7, 7], [7, 8], [15,5],[15,6]])  # Dataset X
epsilon = 0 
k_clusters = 4
depth = 2

# CL_pairs = np.array([])
ML_pairs = np.array([])
CL_pairs = np.array([[2,3],[3,1]])
# # ML_pairs = np.array([[4,5],[0,1],[2,3]])

clustering_problem = max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                                                  features= features,
                                                                  k_clusters= k_clusters,
                                                                  #ML_pairs= ML_pairs,
                                                                  CL_pairs= CL_pairs,
                                                                  epsilon = epsilon,
                                                                  fixed_depth= depth
                                             )


In [ ]:
loandra_path = '/Users/harisrasul/Desktop/loandra'
clustering_problem.solve_loandra(loandra_path)
print(clustering_problem.cluster_assignments)
print(clustering_problem.cluster_diameters)

# Tests for results 

Numerical Datasets

In [ ]:
import numpy as np
import pandas as pd
import openpyxl
from sklearn.preprocessing import LabelEncoder
from satree.utils import * # Dataloader and K-fold mechanism
from satree.SATreeCraft import * # Tree solver framework
from satree.SATreeClassifier import *

In [ ]:
file_path_to_test = '../data/data_banknote_authentication.txt'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/breast+cancer+coimbra/dataR2.csv'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/Cryotherapy.xlsx'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/Immunotherapy.xlsx'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/ionosphere/ionosphere.data'
label_position = -1 
delimiter = ','
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/iris/iris.data'
label_position = -1 
delimiter = ','
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/Data_User_Modeling_Dataset_Hamdi_Tolga_KAHRAMAN.xls'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/vertebral+column/verbex.data'
delimiter = ','
label_position = -1 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/wine/wine.data'
delimiter = ','
label_position = 0 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position)
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


In [ ]:
file_path_to_test = '../data/monk+s+problems/monks-2.train'  # Update this to the path of your data file
delimiter = ' '
label_position = 0 
data_loader = TreeDataLoaderBinaryNumerical(file_path=file_path_to_test, delimiter=delimiter, label_position= label_position, custom_exclude=[-1])
print("Features:", data_loader.features, data_loader.features.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0,
                                                    complete_tree= False)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


Max height Problem - Numerical

In [ ]:
loandra_path = '/Users/harisrasul/Desktop/loandra'

In [ ]:
max_accuracy_numerical_problem = SATreeCraft(dataset=dataset,
                                             features=features,labels=labels,
                                             true_labels_for_points=true_labels_for_points,
                                             classification_objective='max_accuracy',
                                             fixed_depth=3,
                                             # min_support= 5
                                             # min_margin  = 10
                                             # tree_structure= 'Oblivious'
                                             )
max_accuracy_numerical_problem.solve_loandra(loandra_path= loandra_path)
print("Final Model: ", max_accuracy_numerical_problem.model)
print("Min cost found: ", max_accuracy_numerical_problem.min_cost)

Min Height Problem - Numerical

In [ ]:
min_height_numerical_problem = SATreeCraft(dataset=dataset,features=features,labels=labels,true_labels_for_points=true_labels_for_points)
min_height_numerical_problem.solve_loandra(loandra_path)
print("Final Model: ", min_height_numerical_problem.model)
print("min depth found: ", min_height_numerical_problem.min_depth)

K-fold tests accuracies

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth
for depth in depths:
    # Capture the start time
    start_time = time.time()

    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, 
                                                    min_support_level= 0)
    # Capture the end time
    end_time = time.time()

    # Calculate the duration
    duration = end_time - start_time

    # Print or log the results including the time taken
    print(f"Depth: {depth}, Min Support: {minimum_support}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")


Categorical Datasets

In [ ]:
from satree.utils import *
# Example usage:
file_path = '../data/credit+approval/crx.data'
label_index = -1
categorical_feature_index = None  
numerical_indices = np.array([1, 2, 7, 10, 13,14]) 

data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)

# Accessing the processed data
print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth and minimum support level
for depth in depths:
    # Capture the start time
    start_time = time.time()
    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical, 
                                                    min_support_level=0, complete_tree= False)
    # Capture the end time
    end_time = time.time()
    # Calculate the duration
    duration = end_time - start_time
    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")

In [ ]:
# Promoter data set
file_path = '../data/molecular+biology+promoter+gene+sequences/promoters.data'
label_index = 0
categorical_feature_index = 2  
numerical_indices = None
data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)
print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)
features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth and minimum support level
for depth in depths:
    # Capture the start time
    start_time = time.time()
    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical, 
                                                    min_support_level=0, complete_tree= False)
    # Capture the end time
    end_time = time.time()
    # Calculate the duration
    duration = end_time - start_time
    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")

In [ ]:
file_path = '../data/hiv+1+protease+cleavage/746Data.txt'
label_index = 1
categorical_feature_index = 0  # The features are a string at the third element
numerical_indices = None
data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)
# Accessing the processed data
print("Features:", data_loader.features)
print("Categorical Features:", data_loader.features_categorical)
print("Numerical Features:", data_loader.features_numerical)
print("Labels:", data_loader.labels)
print("True Labels for Points:", data_loader.true_labels_for_points)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

dataset = dataset[3::4]
true_labels_for_points = true_labels_for_points[3::4]

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth and minimum support level
for depth in depths:
    # Capture the start time
    start_time = time.time()
    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical, 
                                                    min_support_level=0, complete_tree= False)
    # Capture the end time
    end_time = time.time()
    # Calculate the duration
    duration = end_time - start_time
    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")

In [ ]:
file_path = '../data/soybean+large/soybean-large.data'
label_index = 0
categorical_feature_index = None  # The features are a string at the third element
numerical_indices = None

data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)

# Accessing the processed data
print("Features:", data_loader.features, data_loader.features.shape)
print("Categorical Features:", data_loader.features_categorical, data_loader.features_categorical.shape)
print("Numerical Features:", data_loader.features_numerical, data_loader.features_numerical.shape)
print("Labels:", data_loader.labels, data_loader.labels.shape)
print("True Labels for Points:", data_loader.true_labels_for_points, data_loader.true_labels_for_points.shape)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset

In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth and minimum support level
for depth in depths:
    # Capture the start time
    start_time = time.time()
    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical, 
                                                    min_support_level=0, complete_tree= False)
    # Capture the end time
    end_time = time.time()
    # Calculate the duration
    duration = end_time - start_time
    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")

In [ ]:
file_path = '../data/hiv+1+protease+cleavage/746Data.txt'
label_index = 1
categorical_feature_index = 0  # The features are a string at the third element
numerical_indices = None
data_loader = TreeDataLoaderWithCategorical(
    file_path= file_path,
    label_index= label_index,
    numerical_indices= numerical_indices,
    categorical_feature_index=categorical_feature_index
)
# Accessing the processed data
print("Features:", data_loader.features)
print("Categorical Features:", data_loader.features_categorical)
print("Numerical Features:", data_loader.features_numerical)
print("Labels:", data_loader.labels)
print("True Labels for Points:", data_loader.true_labels_for_points)
print("Dataset:\n", data_loader.dataset,data_loader.dataset.shape)

features = data_loader.features
features_categorical = data_loader.features_categorical
features_numerical = data_loader.features_numerical
labels = data_loader.labels
true_labels_for_points = data_loader.true_labels_for_points
dataset = data_loader.dataset


In [ ]:
import time
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depths = [2,3,4]
# depths = [3,4]
# Iterate through each combination of depth and minimum support level
for depth in depths:
    # Capture the start time
    start_time = time.time()
    # Execute the k-fold tester
    accuracies, mean_score = k_fold_tester(loandra_path=loandra_path,
                                                    k=k, depth=depth, dataset=dataset, 
                                                    true_labels_for_points=true_labels_for_points, 
                                                    labels=labels, features=features, features_categorical=features_categorical, features_numerical=features_numerical, 
                                                    min_support_level=0, complete_tree= False)
    # Capture the end time
    end_time = time.time()
    # Calculate the duration
    duration = end_time - start_time
    # Print or log the results including the time taken
    print(f"Oblivious Depth: {depth}, Time Taken: {duration:.2f} seconds")
    print(f"Accuracies: {accuracies}")
    print(f"Mean Score: {mean_score}\n")

Max Accuracy Categorical

In [ ]:
max_accuracy_categorical_problem = SATreeCraft(dataset=dataset,
                                           features=features,
                                           labels=labels,
                                           true_labels_for_points=true_labels_for_points,
                                           features_categorical=features_categorical,
                                           features_numerical=features_numerical,
                                           classification_objective= 'max_accuracy',
                                           fixed_depth=2,
                                           # min_support= 2,
                                           # tree_structure = 'Oblivious'
                                           )

loandra_path = '/Users/harisrasul/Desktop/loandra'
max_accuracy_categorical_problem.solve_loandra(loandra_path)
print("Final Model: ", max_accuracy_categorical_problem.model)
print("Min cost found: ", max_accuracy_categorical_problem.min_cost)

Min Height Categorical

In [ ]:
min_height_categorical_problem = SATreeCraft(dataset=dataset,
                                           features=features,
                                           labels=labels,
                                           true_labels_for_points=true_labels_for_points,
                                           features_categorical=features_categorical,
                                           features_numerical=features_numerical)
min_height_categorical_problem.solve()
min_height_categorical_problem.export_cnf()
print("Final Model: ", min_height_categorical_problem.model)
print("min depth found: ", min_height_categorical_problem.min_depth)

K-fold Categoircal Test

In [ ]:
loandra_path = '/Users/harisrasul/Desktop/loandra'
k = 5
depth = 2 
minimum_support = 0
accuracies, mean_score = k_fold_tester(k, depth, dataset, true_labels_for_points, labels, features, features_categorical, features_numerical, 
                                       # complete_tree= False
                                       )
                                       
print(accuracies)
print(mean_score)